apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ye2vf1nmf-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:80bfdb8d26f4f887fc41de505491143eaaf45dec@sha256:2870328845b9aa01c48611bf869ff0875f63d1688c43ab0b7318ba8925248d70
          name: container-image
