apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ye2vf1nmf-go
  janus-idp.io/tekton: ye2vf1nmf-go
  backstage.io/kubernetes-id: ye2vf1nmf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ye2vf1nmf-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
